### ISSUE TITLE
Ren'Py 8 to-do list

### ISSUE THREAD

**Issue by TRIDENT1313** [ForeverAndEverTeam/fae-mod#65]
Since Py 2 has been discontinued for a long time, and with Py 3 well on the way, I figure I'll make a to-do list.

Will update as things get checked off.

### Python specifics
- [x] Ensure ALL code meets Python 3 specs/syntax.
- [x] Fiddle with the returns, and update definitions where needed.
- [x] Filter logs into a single logging system instead of having sperate logs.
- [x] Update submod framework to Python 3 specifics (might end up not doing this, as it works now, but might need to be used later)
### Game specific.

- [x] Ensure notifications work as expected, as these have recently stopped working. closes #61 
- [x] ~~Refactor Minigames~~ (Won't do this since I don't have the patience for it)
- [x] #66
- [x] Finish adding exps to the topics, check for deprecated letter.
- [x] Import topics to code.
- [x] Verify backup system works properly.
- [x] Add extends to topics since, good god, we need them.
- [x] #59 stuff

**Comment by TRIDENT1313** [comment]
[Closing as done]
